# Generated by Django 5.0.4 on 2024-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_descricao_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_material',
            field=models.CharField(default='', max_length=7),
        ),
    ]
