# Generated by Django 5.0.4 on 2024-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_rename_produto_materiaprima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='valor_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
