# Generated by Django 5.0.4 on 2024-05-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_materiaprima_valor_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='materiaprima',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='imagem_produto'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.CharField(default='', max_length=7)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('quantidade', models.IntegerField()),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_peca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
    ]
