# Generated by Django 5.0.4 on 2024-05-05 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_linhaproduto_tipomadeira_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='00000000000100', max_length=14, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter 14 dígitos', regex='^\\d{14}$')])),
                ('razao_social', models.CharField(default='', max_length=255)),
                ('endereco', models.CharField(default='', max_length=255)),
                ('contato', models.CharField(default='99999999999', max_length=11, validators=[django.core.validators.RegexValidator(message='Contato deve conter 11 dígitos', regex='^\\d{11}$')])),
            ],
        ),
        migrations.AddField(
            model_name='mercadoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.CharField(default='', max_length=7)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('quantidade', models.IntegerField()),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_peca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
                ('fornecedores', models.ManyToManyField(related_name='materias_primas', to='estoque.fornecedores')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='lista_insumos',
            field=models.ManyToManyField(related_name='fornecedores_rel', to='estoque.materiaprima'),
        ),
    ]
