# Generated by Django 5.0.4 on 2024-05-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_mercadoria_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.mercadoria'),
        ),
    ]
