# Generated by Django 5.0.4 on 2024-05-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_remove_imagem_produto_imagem_materia_prima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
