# Generated by Django 5.0.4 on 2024-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_delete_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='imagens',
            field=models.ImageField(blank=True, upload_to='materiasprimas/'),
        ),
    ]
