# Generated by Django 5.0.4 on 2024-05-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_imagem_mp_rename_mercadoria_produto_imagem_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem_produto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
    ]
