# Generated by Django 5.0.4 on 2024-05-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_imagem_produto_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='P_V_MDF',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='P_V_Terc',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='P_V_madeira_4x',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='custo_final',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='custo_madeira',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fundo_total_x4',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='lucro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_sugerido',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_venda',
        ),
    ]
