# Generated by Django 5.0.4 on 2024-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_remove_produto_p_v_mdf_remove_produto_p_v_terc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagens_produto',
            field=models.ImageField(blank=True, upload_to='imgprodutos/'),
        ),
    ]
