# Generated by Django 5.0.4 on 2024-05-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_fornecedores_slug_produto_imagens_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='valor_m2',
        ),
    ]
