# Generated by Django 5.0.4 on 2024-05-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_remove_materiaprima_valor_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='fornecedores',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='imagens',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='fornecedor',
            field=models.ManyToManyField(related_name='materias_primas', to='estoque.fornecedores'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='imagens_MP',
            field=models.ImageField(blank=True, upload_to='imagem_materiasprimas/'),
        ),
    ]
