# Generated by Django 5.0.4 on 2024-05-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_remove_materiaprima_fornecedores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiaprima',
            old_name='fornecedor',
            new_name='fornecedores',
        ),
    ]
