# Generated by Django 5.0.4 on 2024-05-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_alter_materiaprima_imagens_mp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
