# Generated by Django 5.0.4 on 2024-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_produto_p_v_mdf_x2_produto_p_v_madeira_x4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='estoque_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_min',
            field=models.IntegerField(default=0),
        ),
    ]
